#ifndef EXLINK_JTAG_BRIDGE_JTAG_PROTOCOL_H
#define EXLINK_JTAG_BRIDGE_JTAG_PROTOCOL_H

#include <stdint.h>

#ifndef EXLINK_JTAG_PERFORMANCE_MODE
#define EXLINK_JTAG_PERFORMANCE_MODE 1
#endif

#if EXLINK_JTAG_PERFORMANCE_MODE
#ifndef EXLINK_JTAG_USE_FAST_TX_PACK
#define EXLINK_JTAG_USE_FAST_TX_PACK 1
#endif
#ifndef EXLINK_JTAG_USE_FAST_RX_PACK
#define EXLINK_JTAG_USE_FAST_RX_PACK 1
#endif
#ifndef EXLINK_JTAG_USE_LARGE_DMA_CHUNK
#define EXLINK_JTAG_USE_LARGE_DMA_CHUNK 1
#endif
#ifndef EXLINK_JTAG_USE_LARGE_SHIFT
#define EXLINK_JTAG_USE_LARGE_SHIFT 1
#endif
#ifndef EXLINK_JTAG_USE_BATCHED_CDC
#define EXLINK_JTAG_USE_BATCHED_CDC 1
#endif
#ifndef EXLINK_JTAG_USE_REDUCED_CHUNK_RESET
#define EXLINK_JTAG_USE_REDUCED_CHUNK_RESET 1
#endif
#else
#undef EXLINK_JTAG_USE_FAST_TX_PACK
#define EXLINK_JTAG_USE_FAST_TX_PACK 0
#undef EXLINK_JTAG_USE_FAST_RX_PACK
#define EXLINK_JTAG_USE_FAST_RX_PACK 0
#undef EXLINK_JTAG_USE_LARGE_DMA_CHUNK
#define EXLINK_JTAG_USE_LARGE_DMA_CHUNK 0
#undef EXLINK_JTAG_USE_LARGE_SHIFT
#define EXLINK_JTAG_USE_LARGE_SHIFT 0
#undef EXLINK_JTAG_USE_BATCHED_CDC
#define EXLINK_JTAG_USE_BATCHED_CDC 0
#undef EXLINK_JTAG_USE_REDUCED_CHUNK_RESET
#define EXLINK_JTAG_USE_REDUCED_CHUNK_RESET 0
#endif

#if EXLINK_JTAG_USE_LARGE_SHIFT
#define EXLINK_JTAG_MAX_SHIFT_BITS  131072u
#else
#define EXLINK_JTAG_MAX_SHIFT_BITS  32768u
#endif

#define EXLINK_JTAG_MAX_SHIFT_BYTES ((EXLINK_JTAG_MAX_SHIFT_BITS + 7u) / 8u)

void jtag_protocol_init(void);
void jtag_protocol_task(void);

#endif
